version: "3.7"
networks:
  mysql-network:
    external: true
    name: $DOCKER_NETWORK
  mynetwork:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    working_dir: /var/www/
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    networks:
      - mysql-network
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'XDEBUG_MODE=on'

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - mynetwork
